### PR TITLE
Fix sympy_check crash on unevaluated trig and complex expressions

### LINKED ISSUE #14442: `<pl-symbolic-input>` behaves unexpectedly with non-real answers
### Details

Reported by @abowers-ucsd on Slack.

For `<pl-symbolic-input>`, submitting a non-real answer using a real variable when `allow-complex` is not set to "true" causes an automatic issue that reports `HasComplexError: complex values not allowed`.

Below is a minimal example. The actual exercise or correct answer is not relevant to the issue. Entering an answer such as `log(-x^2)` or `sqrt(-x^2)` will result in the error because of the assumption that the variable x is real. Removing `real="True"` from `x = sympy.symbols("x", real="True")` or adding `allow-complex="true"` will stop the error from happening.

```html
<pl-question-panel>
  <p>
    Solve the initial value problem $$\frac{dy}{dx} = -\dfrac{1}{x^2}, \qquad y(1) = 0$$
  </p>
</pl-question-panel>


<pl-symbolic-input
  answers-name="ans"
  label="$y(x)=$"
  variables="x"
></pl-symbolic-input>
```

```py
import prairielearn as pl
import sympy

def generate(data):
    x = sympy.symbols("x", real="True")

    ans = x**(-1)-1
    
    data["correct_answers"]["ans"] = pl.to_json(ans)
```

### PR DESCRIPTION
**Pull request by nwalters512**
# Description

Fixes two crashes in `pl-symbolic-input` introduced by #14407, plus a small refactor to `validate_string_as_sympy`.

## Bug 1: Complex expressions from real variable assumptions (closes #14442)

When a correct answer uses `sympy.symbols("x", real=True)`, submitting an expression like `log(-x^2)` or `sqrt(-x^2)` raises an unhandled `HasComplexError` during parse. This happened because `validate_string_as_sympy` was called without variable assumptions — so the expression passed validation — but the subsequent `convert_string_to_sympy` call with assumptions detected the expression as complex and raised an unhandled error.

**Fix:** Added an `assumptions` parameter to `validate_string_as_sympy` so it catches assumption-induced complex expressions through its existing error handling.

## Bug 2: Unevaluated trig functions with `display-simplified-expression="false"`

Submitting expressions containing `sec()` or `csc()` (e.g. `sec(0)`, `(16-9*(sec(0)^2))/3`) crashes with `AttributeError: 'One' object has no attribute '_eval_is_extended_real'`. This is a sympy bug triggered by the `is_extended_real` check added in #14407 — sympy's `sec._eval_is_extended_real()` calls `_reciprocal_of(cos(0))` which returns `One`, and `One` doesn't implement `_eval_is_extended_real`.

**Fix:** Catch `AttributeError` in `sympy_check` and skip the complex-number check for items where sympy's assumption system can't resolve the query. Also changed `item == sympy.I` to `item is sympy.I` since `ImaginaryUnit` is a singleton.

## Refactor: `validate_string_as_sympy` return type

Changed the return type from `str | None` to `str | sympy.Expr` — on error it returns the error message string (as before), on success it returns the parsed expression. This eliminates the redundant `convert_string_to_sympy` call in `pl-symbolic-input`'s `parse()`, which was previously parsing the expression twice (once for validation, once for the result).

There are additional call sites in `pl-symbolic-input` and `pl-big-o-input` (in `render()` and `grade()`) that still call `convert_string_to_sympy` directly and could potentially be migrated to use `validate_string_as_sympy` or `json_to_sympy` instead. That's a larger refactor left for a follow-up.

Majority of implementation done with AI assistance.

# Testing

- Added 7 new pytest cases across `pl-symbolic-input_test.py` and `sympy_utils_test.py` covering both bugs. All fail on master and pass with this fix.
- All 692 tests across `sympy_utils_test.py`, `pl-symbolic-input_test.py`, and `pl-big-o-input` pass.

To reproduce bug 1:
- Create a question with `<pl-symbolic-input answers-name="ans" variables="x">` and a `server.py` that uses `x = sympy.symbols("x", real=True)`
- Submit `log(-x^2)` → should show format error, not crash

To reproduce bug 2:
- Create a question with `<pl-symbolic-input answers-name="ans" variables="x" display-simplified-expression="false">`
- Submit `sec(0)` or `(16-9*(sec(0)^2))/3` → should parse successfully, not crash

### CODE REVIEW

File: apps/prairielearn/elements/pl-symbolic-input/pl-symbolic-input.py [hunk 1]
```diff
@@ -509,38 +509,31 @@ def parse(element_html: str, data: pl.QuestionData) -> None:
...
-        return
-
     # Retrieve variable assumptions encoded in correct answer
     assumptions_dict = None
     a_tru = data["correct_answers"].get(name, {})
     if isinstance(a_tru, dict):
         assumptions_dict = a_tru.get("_assumptions")
 
-    a_sub_parsed = psu.convert_string_to_sympy(
+    result = psu.validate_string_as_sympy(
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-symbolic-input/pl-symbolic-input.py]: It's both cleaner and faster to avoid double-parsing. This came out of me noticing that we had two functions with essentially identical signatures that did very similar things. I felt it was better to refactor to help fix things.

As noted in the PR body, there's really no reason for _anyone_ to be calling `convert_string_to_sympy` now, but I avoided doing a larger refactor in this PR. We could consider following up with that if we felt it's high-value.

**Comment by reteps** [comment]
Thanks @austinbillings-pl , can you request review in these scenarios? Then it shows up on my list 👍

File: apps/prairielearn/python/prairielearn/sympy_utils.py [hunk 2]
```diff
@@ -826,11 +836,12 @@ def validate_string_as_sympy(
     custom_functions: list[str] | None = None,
     imaginary_unit: str | None = None,
     simplify_expression: bool = True,
-) -> str | None:
-    """Try to parse expr as a SymPy expression. If it fails, return a string with an appropriate error message for display on the frontend.
+    assumptions: AssumptionsDictT | None = None,
+) -> str | sympy.Expr:
```
Comment (nwalters512) [inline apps/prairielearn/python/prairielearn/sympy_utils.py]: I just realized that this is technically part of our public API, and there are checks in the wild that are using `is not None` to detect an error case :/

So this isn't safe to merge as-is unfortunately. I'll give this some more thought.

Comment (nwalters512) [reply apps/prairielearn/python/prairielearn/sympy_utils.py]: In 0ed4047 I introduced a new `try_parse_string_as_sympy` function that returns a discriminated union to force callers to handle error states. `validate_string_as_sympy` now uses it internally. Both `validate_string_as_sympy` and `convert_string_to_sympy` remain for backwards compatibility, and their APIs are unchanged.

File: apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py [hunk 3]
```diff
@@ -268,15 +268,15 @@ def parse(element_html: str, data: pl.QuestionData) -> None:
         data["submitted_answers"][name] = None
         return
 
-    s = psu.validate_string_as_sympy(
+    result = psu.try_parse_string_as_sympy(
```
Comment (reteps) [inline apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py:271]: Consider `safe_parse` (mirror Zod naming)

File: apps/prairielearn/python/prairielearn/sympy_utils.py [hunk 4]
```diff
@@ -826,11 +849,12 @@ def validate_string_as_sympy(
...
     simplify_expression: bool = True,
-) -> str | None:
-    """Try to parse expr as a SymPy expression. If it fails, return a string with an appropriate error message for display on the frontend.
+    assumptions: AssumptionsDictT | None = None,
+) -> SympyParseResult:
+    """Try to parse expr as a SymPy expression.
 
     Returns:
-        `None` if the expression is valid, and an error message otherwise.
+        A parsed SymPy expression on success, or a formatted error message on failure.
```
Comment (reteps) [inline apps/prairielearn/python/prairielearn/sympy_utils.py:857]: consider an example.

File: apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py (hunk 3 above)
Comment (nwalters512) [reply apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py:271]: The `try_` prefix mirrors C#'s `TryParse` and Rust's `try_from`/`try_into` conventions — functions that return a result type instead of throwing. It also fits naturally with the existing `convert_string_to_sympy` / `validate_string_as_sympy` naming family.

*— Claude*

File: apps/prairielearn/python/prairielearn/sympy_utils.py (hunk 4 above)
Comment (nwalters512) [reply apps/prairielearn/python/prairielearn/sympy_utils.py:857]: Resolved in d14426f — added a usage example to the docstring.

*— Claude*

File: apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py (hunk 3 above)
Comment (nwalters512) [reply apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py:271]: As for me: I think that we don't gain much by trying to mirror TypeScript APIs or conventions in Python.
